### ISSUE TITLE
剪裁框实时显示尺寸或者比例

### ISSUE THREAD

**Issue by sunlei4076** [chengpeiquan/vue-picture-cropper#11]
可以在剪裁框的顶角上显示比例或者宽高尺寸信息吗

**Comment by chengpeiquan** [comment]
你好啊，这一类信息加在裁剪区域里显示似乎对用户操作感觉有点干扰，不妨在项目里把这些信息单独显示在裁剪框的下方？裁剪比例和裁剪结果大小都是项目在开发的时候指定传入，不需要通过插件来处理获取的
