### ISSUE TITLE
裁剪结果底部有透明部分

### ISSUE THREAD

**Issue by XAIOS** [chengpeiquan/vue-picture-cropper#12]
## 环境
- vue^3.0.5
- vue-picture-cropper^0.1.11

## 代码
```html
<picture-cropper :box-style='{ height: "40vh" }' :options='cropper_config' :img='cropper_img' />
```

```javascript
const cropper_img = ref('')
const cropper_config = ref({ viewMode: 1 })
// -------------------------------------------------------------------
const reader = new FileReader
reader.onload = () => {
  cropper_img.value = reader.result
}
reader.readAsDataURL(image)
// -------------------------------------------------------------------
new File([cropper.getBlob()], 'crop.jpg', { type: 'image/jpeg' })
```

## 效果（上传后会因为转成 jpeg 而有一条底线）
![image](https://user-images.githubusercontent.com/23434033/131523648-f3f7bbc6-bb4f-441f-a5a4-c1c4ca53fb17.png)
![image](https://user-images.githubusercontent.com/23434033/131523772-3aa78e5d-4a6f-4389-8e6f-cf273878921b.png)

**Comment by XAIOS** [comment]
经测试，仅 `getBlob` 存在此问题，`getDataURL` 正常

**Comment by chengpeiquan** [comment]
收到，我稍后跟进哈

**Comment by chengpeiquan** [comment]
不好意思，上周一直在赶公司的事情，今天把问题处理了一下，麻烦安装最新版本试试~
测试了多种从 base64 转换为 blob 的方案，在大图片的情况下仍存在白边的情况，所以从 0.3.0 版本改成用 canvas 去获取，但也因此需要改成异步方式，我已更新到 [README](https://github.com/chengpeiquan/vue-picture-cropper#%E5%B8%B8%E7%94%A8%E6%96%B9%E6%B3%95) 里了，多谢反馈！
