### ISSUE TITLE
怎么在同个页面渲染两个裁切插件呢

### ISSUE THREAD

**Issue by dga3364** [chengpeiquan/vue-picture-cropper#16]
是有ref这类的渲染吗

**Comment by chengpeiquan** [comment]
之前没考虑过这个场景，等我晚点忙完来跟进一下哈

**Comment by chengpeiquan** [comment]
你好，已在 0.5.0 版本里增加了支持
https://github.com/chengpeiquan/vue-picture-cropper#%E5%A4%9A%E4%B8%AA%E8%A3%81%E5%89%AA%E6%A1%86
