### ISSUE TITLE
报错无法使用

### ISSUE THREAD

**Issue by maoweifan** [chengpeiquan/vue-picture-cropper#20]
<img width="877" alt="image" src="https://user-images.githubusercontent.com/51221758/172776558-f4276739-60c4-4327-9f81-22e1d44e74cd.png">

vue@3.2.36

**Comment by chengpeiquan** [comment]
回来试了一下没能复现，能否提供一个有问题的演示代码我排查下原因？我刚升级了 demo 的依赖后也没有出现这个问题，也可以先参考下 demo  
https://github.com/chengpeiquan/vue-picture-cropper-demo
