### ISSUE TITLE
nuxt3中渲染很慢

### ISSUE THREAD

**Issue by Upose** [chengpeiquan/vue-picture-cropper#26]
我尝试在nuxt3中使用这个插件，但是为什么图片渲染到裁剪框的时间非常长呢，然后如果第二次在选择这张图，渲染又会很快，换别的图又慢了，
 reader.readAsDataURL(file)
      reader.onload = () => {
        // Update the picture source of the `img` prop
        pic.value = String(reader.result)
        // Show the modal
        isShowModal.value = true
        // Clear selected files of input element
        if (!uploadInput.value) return
        uploadInput.value.value = ''
      }
按照官方给的渲染方法做的 我以前在vue3里面用过，没有出现这个问题

**Comment by Upose** [comment]
> 我尝试在nuxt3中使用这个插件，但是为什么图片渲染到裁剪框的时间非常长呢，然后如果第二次在选择这张图，渲染又会很快，换别的图又慢了， reader.readAsDataURL(file) reader.onload = () => { // Update the picture source of the `img` prop pic.value = String(reader.result) // Show the modal isShowModal.value = true // Clear selected files of input element if (!uploadInput.value) return uploadInput.value.value = '' } 按照官方给的渲染方法做的 我以前在vue3里面用过，没有出现这个问题

    "nuxt": "^3.0.0",
    "vue-picture-cropper": "0.6.0"

**Comment by chengpeiquan** [comment]
我创建了一个 Nuxt 3 的 demo ，本地 dev 和部署到 GitHub Pages 上都没有感觉到慢。
这个是源码 https://github.com/chengpeiquan/vpc-nux3-demo
这个是部署 https://chengpeiquan.github.io/vpc-nux3-demo
我这边图片的渲染都是秒开，试试克隆这个仓库在本地跑起来看看慢不慢

**Comment by Upose** [comment]
> 我创建了一个 Nuxt 3 的 demo ，本地 dev 和部署到 GitHub Pages 上都没有感觉到慢。 这个是源码 https://github.com/chengpeiquan/vpc-nux3-demo 这个是部署 https://chengpeiquan.github.io/vpc-nux3-demo 我这边图片的渲染都是秒开，试试克隆这个仓库在本地跑起来看看慢不慢

不好意思 前两天阳了  我今天又来试了一下，速度是正常的   我也没有改代码，不知道上次什么原因

**Comment by chengpeiquan** [comment]
> 不好意思 前两天阳了 我今天又来试了一下，速度是正常的 我也没有改代码，不知道上次什么原因

注意身体啊！我们办公室也是阳了好几个，我感觉我也在边缘徘徊…
那我先关闭这个 issue 了哈，后面如果再遇到再看看~
