### ISSUE TITLE
如果用v-if控制会出现获取不到图片，有两个裁剪框

### ISSUE THREAD

**Issue by lime2008** [chengpeiquan/vue-picture-cropper#34]
如题，如果在<vue-picture-cropper />标签外套一层由v-if控制的div
如果使用v-if第一次关闭，用cropper.getFile()方法获取到的内容为null
并且再次加载不同的图片，会出现两个裁剪框，新图片在上面，原来的图片在下面，再次用getFile方法获取到的file返回的是上方图片裁剪后的文件
但是用v-show控制就正常

**Comment by chengpeiquan** [comment]
不好意思昨天太忙现在才来跟进，类似文档上的 demo 这样通过子组件的形式先把功能写好，再在需要的地方多次引入该子组件，操作上没有遇到什么问题（或者是我的常规操作没能发现）

- [多裁剪框的 demo 例子](https://cropper.chengpeiquan.com/zh/multiple-cropper.html)
- [多裁剪框的 demo 代码](https://github.com/chengpeiquan/vue-picture-cropper/blob/main/docs/components/MultipleCropper.vue)

如果是在同一个组件里直接渲染多次 `<VuePictureCropper />` 确实是有问题的，因为之前比较忙，加上对这个使用场景的人似乎很少（按照目前收到的反馈来看），所以一直拖着没处理 _(:з)∠)_ 我找个时间来修一下~

如果说不是这种情况遇到的话，看能否提供个能复现问题的 demo ，我来针对场景排查下

**Comment by lime2008** [comment]
```vue
<script setup lang="ts">
  import { ref, Ref } from "vue";
  import axios from "axios";
  import VuePictureCropper, { cropper } from "vue-picture-cropper";
  const pic = ref("");
  const uploadInput: Ref<HTMLInputElement | null> = ref(null);
  const crop_show = ref(false);
  const selectFile = (e: Event) => {
    let result = { dataURL: "", blobURL: "" };
    crop_show.value = true;
    result.dataURL = "";
    result.blobURL = "";
    const { files } = e.target as HTMLInputElement;
    if (!files || !files.length) return;
    const file = files[0];
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      pic.value = String(reader.result);
      if (uploadInput.value == null) return;
      uploadInput.value.value = "";
    };
  };
  const upload_mode = ref("avatar");
  const getResult = async () => {
    if (!cropper) return;
    const file = await cropper.getFile({
      fileName: "1"
    });
    console.log(file);
    const formData = new FormData();
    formData.append("file", file as Blob);
    axios
      .post("https://sq.lihouse.xyz/upload/" + upload_mode.value, formData, {
        headers: {
          "Content-Type": "multipart/form-data"
        }
      })
      .then(async (response) => {
        crop_show.value = false;
        let data = response.data;
        if (data.status) {
          console.log(data.reason);
        } else {
          console.log(data.reason);
        }
        /*      await submit();
        refresh();*/
      })
      .catch((error) => {
        console.log(error);
      });
  };
</script>

<template>
  <div class="avatar" @click="upload_mode = 'avatar';">
    <input
      style="
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        font-size: 0;
        cursor: pointer;
        opacity: 0;
      "
      ref="uploadInput"
      type="file"
      accept="image/jpg, image/jpeg, image/png, image/gif"
      @change="selectFile"
    />
  </div>
  <div v-if="crop_show">
    <vue-picture-cropper
      :boxStyle="{
      width: '350px',
      height: '350px',
      backgroundColor: '#f8f8f8',
      margin: 'auto'
    }"
      :img="pic"
      :options="{
      viewMode: 1,
      dragMode: 'crop',
      aspectRatio: 1 / 1,
    }"
    />
  </div>
  <button @click="getResult()">提交</button>
</template>

<style scoped>
  .avatar {
    background-color: #ffffff;
    height: 100px;
    width: 100px;
  }
</style>
```
我摘了段代码，上面的可以复现。因为用的不多，所以没有写组件ヾ(≧▽≦*)o

**Comment by chengpeiquan** [comment]
> 我摘了段代码，上面的可以复现。因为用的不多，所以没有写组件ヾ(≧▽≦*)o

好嘞，谢谢~

**Comment by chengpeiquan** [comment]
Hi ，这份示例代码我跑了一下，并在我的这个插件和 Cropperjs 都开了调试，发现这里的情况不是之前存在的问题（事实上那个用法确实应该很少人用，并且我给了不会出问题的 demo 示例，基本上应该可以规避那种奇怪的用法，不过我后面还是会处理一下的）。

说说这段示例代码的吧，这里确实是有两个问题，咱们来逐一分析下：

### 第一个问题

第一个问题是 `cropper.getFile()` 拿到的一直是 `null` ，调试了一圈，最终定位到问题是来自 Cropperjs 本身

我先简单说下 File 数据的获取流程， `cropper.getFile()` 这个方法是我自己提供的，前置操作是通过 `cropper.getBlob()` 方法（也是我自己提供的）获取一个 Blob 对象，这个方法调用了 Cropperjs 提供的 `getCroppedCanvas()` 方法，如果过程中出现错误，进入 `try / catch` 的 `catch` 分支就会返回 `null` ，示例代码最终拿到的 `null` 就是这里来的。

之所以会进入 `catch` 分支，是因为 Cropperjs 的 `getCroppedCanvas()` 方法也返回了 `null` ，在它的源码 [methods.js#L640-L642](https://github.com/fengyuanchen/cropperjs/blob/main/src/js/methods.js#L640-L642) 里面有一段处理异常拦截的判断：

```js
  getCroppedCanvas(options = {}) {
    if (!this.ready || !window.HTMLCanvasElement) {
      return null;
    }
    //...
```

经过调试，是因为 `this.ready` 这个条件为 `false` 导致了被拦截，但事实上， Cropperjs 的实例是初始化成功的（否则我提供的 `cropper` 实例也是初始值 `null` ，而不会被初始化），这一点通过 `@ready` 事件也可以验证。

在调试过程中也验证了 Cropperjs 本身在 Render 后，这个 `this.ready` 也确实被设置为 `true` 了，并且没有再更改为 `false` ，所以这个问题就很诡异了，不是很确定 `getCroppedCanvas()` 是怎么得到的 `this.ready` 为 `false` 。

我搜索了 Cropperjs 仓库的相关 Issue ，这个问题至少在 2017 年就已经出现了，反馈的也不算少，不过原作者一直没有明确的原因告知和给出具体的解决方案。

目前我是参考了 2022 算是比较近期的一个回复，作者给了相对明确的修复建议 ---> [getCroppedCanvas always returns null](https://github.com/fengyuanchen/cropperjs/issues/905#issuecomment-1013046325)

>You SHOULD initialize the Cropper only when the dialog is shown completely:
>Append the image into the dialog body.
>Show the dialog.
>Check if the image is displayed in the right size and position (This is the most important step).
>Apply Cropper.js on the image, then the image will be displayed correctly in the cropper area.

在这个建议下，我把你的代码稍微改了一下，加了 50ms 的延迟，确实解决了问题，  `cropper.getFile()`  不再拿到 `null` ，可以正确拿到 File 数据。

```diff
const selectFile = (e: Event) => {
  crop_show.value = true
+  setTimeout(() => {
    result.dataURL = ''
    result.blobURL = ''
    const { files } = e.target as HTMLInputElement
    if (!files || !files.length) return
    const file = files[0]
    const reader = new FileReader()
    reader.readAsDataURL(file)
    reader.onload = () => {
      pic.value = String(reader.result)
      if (uploadInput.value == null) return
      uploadInput.value.value = ''
    }
+  }, 50)
}
```

关于这个情况我看看后面找个时间跟原作者沟通一下。

### 第二个问题

第二个问题是重新选择图片后会再次出现裁剪框，示例代码把 `crop_show.value = true` 之后，流程结束后没有再设置为 `false` ，因此我的插件也没有触发组件卸载的生命周期，不会销毁第一次的实例，但这个其实问题不大，因为没有销毁的情况下，我这边是不会重新走初始化流程的，只会通过 `cropper.replace` 更新实例（我自己内部的 `init()` 方法事实上也没有再次触发，所以不是走我的流程）。

由于 Cropperjs 第一个内部问题的存在，所以重新选择图片后，我这边触发了 `cropper.replace` ，可能因为 Cropperjs 的内部机制原因（暂时没有定位的那么细， = = 帮别人 Debug 好累）， Cropperjs  自己会重新走一次它内部的初始化流程，所以会再次触发 `@ready` 事件。

定位到了原因后，随着第一个问题的解决，第二个问题也就没有了~

目前的话，我个人建议是先通过我上面第一个问题的解决方法先处理下，或者是按照我的 demo 那样，拆分子组件来处理。

**Comment by lime2008** [comment]
天呐，谢谢，万分感谢！！！！！！
12点还真有点晚了呢，作者还是好好休息一下比较好~
