### ISSUE TITLE
关于cropper对象多实例的问题

### ISSUE THREAD

**Issue by in-vane** [chengpeiquan/vue-picture-cropper#45]
我看了文档中的例子，想问一下是不是不能同时存在多个裁剪区域各自工作？比如页面上并列两个，那么只有一个裁剪框，另一个裁剪框会消失。

**Comment by chengpeiquan** [comment]
因为最开始采用了一个 export let cropper: CropperInstance | null  的变量设计，带来了一些副作用。

我有想重新设计为 hook 的形式来解决，不过去年换工作后一直在给公司项目追进度，闲下来的时候也有其他想弄的东西，就一直拖着..

**Comment by in-vane** [comment]
好的嘛，那暂时只好用弹窗来规避了
