### ISSUE TITLE
vue3.0.5  配合vite   导入的cropper  在getResult ,clear 等回调里是null

### ISSUE THREAD

**Issue by guozhenyu666** [chengpeiquan/vue-picture-cropper#6]
<template>
  
  <section class="section">
    <p>请先点击按钮选择图片，会进入裁切处理环节</p>

    
    <button class="select-picture">
      <span>选择图片</span>
      <input
        ref="uploadInput"
        type="file"
        accept="image/jpg, image/jpeg, image/png, image/gif"
        @change="selectFile"
      />
    </button>
    
  </section>
  <section class="section" v-if="result">
    <p>裁切后的Base64图片预览：</p>
    <div class="preview6688" ref="preview">
      <img :src="result" alt="组合式 API" />
    </div>
    <p>可以按 F12 查看打印的 base64 / blob 结果</p>
  </section>
  

  
  <div>
    <button @click="isShowDialog = false">取消</button>
    <button @click="clear">清除</button>
    <button @click="reset">重置</button>
    <button @click="getResult">裁切</button>

    
    <vue-picture-cropper
      :boxStyle="{
        width: '100%',
        height: '100%',
        backgroundColor: '#f8f8f8',
        margin: 'auto',
      }"
      :img="pic"
      :options="{
        viewMode: 1,
        dragMode: 'crop',
        aspectRatio: 16 / 9,
        preview: '.preview6688',
      }"
    />
    
  </div>
  
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";
import VuePictureCropper, { cropper } from "vue-picture-cropper";

export default defineComponent({
  components: {
    VuePictureCropper,
  },
  setup() {
    const uploadInput = ref<HTMLInputElement | null>(null);
    const pic = ref<string>("");
    const result = ref<string>("");
    const isShowDialog = ref<boolean>(false);

    /**
     * 选择图片
     */
    const selectFile = (e: Event): void => {
      // 获取选取的文件
    

      const target = e.target as HTMLInputElement;
      const { files } = target;
    

      if (!files) return;
      const file: File = files[0];

      // 转换为base64传给裁切组件
      const reader: FileReader = new FileReader();
  
      reader.readAsDataURL(file);
      reader.onload = (): void => {
        // 更新裁切弹窗的图片源
        pic.value = String(reader.result);
 

    

        // 显示裁切弹窗

 
        // 清空已选择的文件
        if (!uploadInput.value) return;
        uploadInput.value.value = "";
      };
    };

    /**
     * 获取裁切结果
     */
    const getResult = (): void => {
     
      // 获取生成的base64图片地址
      const base64: string = cropper.getDataURL();

      // 获取生成的blob文件信息
      const blob: Blob = cropper.getBlob();

  

      // 把base64赋给结果展示区
      result.value = base64;

      // 隐藏裁切弹窗
      isShowDialog.value = false;
    };

    /**
     * 清除裁切框
     */
    const clear = (): void => {
      cropper.clear();
    };

    /**
     * 重置默认的裁切区域
     */
    const reset = (): void => {
      cropper.reset();
    };

    return {
      // 数据
      uploadInput,
      pic,
      result,
      isShowDialog,

      // 方法
      selectFile,
      getResult,
      clear,
      reset,
    };
  },
});
</script>

<style scoped>
.section {
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 100%;
  max-width: 1200px;
  margin: 0 auto 40px;
}
.section:last-child {
  margin-bottom: 0;
}
.section .select-picture {
  position: relative;
  margin-bottom: 1em;
}
.section .select-picture input {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  opacity: 0;
}
.section .preview {
  display: flex;
  justify-content: center;
  width: 100%;
  max-width: 800px;
  margin-bottom: 1em;
}
.section .preview img {
  width: auto;
  height: auto;
  max-width: 100%;
  max-height: 100%;
}
</style>

**Comment by chengpeiquan** [comment]
不好意思这几天赶项目加班，现在才来跟进，我刚刚跑了个 Vite 的 demo，发现确实拿不到，在 Vue-CLI 的同样版本就正常，等我这两天把项目赶完上线来看下具体是什么原因哈，我明天还要再回去加班，可能还抽不出时间 (｡•́︿•̀｡)

**Comment by guozhenyu666** [comment]
能抽空修一下吗. 想在项目使用这个, 挺急的  , 如果暂时无法修复, 有别的包推荐么?

**Comment by chengpeiquan** [comment]
> 能抽空修一下吗. 想在项目使用这个, 挺急的 , 如果暂时无法修复, 有别的包推荐么?

你好，我刚发布了一个小版本，麻烦安装一下 `0.1.8` 版本试试

引入的时候需要改成从 `esm` 版本导入：

```js
import VuePictureCropper, { cropper } from 'vue-picture-cropper/dist/esm'
```

我这边试了一下在 vite demo 里可以正常使用了（README 等我晚上回去再完善一下）

**Comment by guozhenyu666** [comment]
好的 , 明天我去试试. 可以的话就写进项目了. 谢谢大佬

**Comment by guozhenyu666** [comment]
产出blob 值 有时候是无效的 但是很奇怪 切换页卡之后 又能展示 
产出的blob 值
![无效](https://user-images.githubusercontent.com/49642933/121365097-f0e22180-c96a-11eb-84f3-d79f578ee89c.png)

页面不展示
切换页卡之后 又展示
![有效2](https://user-images.githubusercontent.com/49642933/121365140-f93a5c80-c96a-11eb-9b68-b13fb4cc16be.png)

这个是什么bug  
会导致裁切上传  上传的是全黑无效图片    平均上传三次触发一次bug

**Comment by guozhenyu666** [comment]
https://user-images.githubusercontent.com/49642933/121365635-664df200-c96b-11eb-95d7-8d261d8f2d6c.mp4

**Comment by chengpeiquan** [comment]
跑了一样的blob作为图片src去展示，未能复现这个情况噢，能提供一下浏览器版本和vite的版本号吗？

https://user-images.githubusercontent.com/24845958/121467041-f8e1a600-c9ea-11eb-87da-b88723db4577.mp4

**Comment by guozhenyu666** [comment]
![image](https://user-images.githubusercontent.com/49642933/121489023-3bfd4280-ca06-11eb-87b2-68dbc34f8640.png)

**Comment by guozhenyu666** [comment]
[vite-project.zip](https://github.com/chengpeiquan/vue-picture-cropper/files/6629517/vite-project.zip)
你运行下 都在里面了

https://user-images.githubusercontent.com/49642933/121489092-51726c80-ca06-11eb-9790-8730c8263e01.mp4

**Comment by chengpeiquan** [comment]
我们的版本是一样的，跑了你的代码还是未能复现，我去搜下是什么情况……

话说服务端如果不能单纯接收 input 的 file，只能用 blob 的话，尝试下先用 base64 转 blob ，网上很多实现方法，看看哪个方式在你那边不会出现这个异常？

![1](https://user-images.githubusercontent.com/24845958/121491925-f8f09e80-ca08-11eb-8d53-b97e090318c3.jpg)

https://user-images.githubusercontent.com/24845958/121491944-fd1cbc00-ca08-11eb-959a-250a3ccbc3c6.mp4

https://user-images.githubusercontent.com/24845958/121491961-01e17000-ca09-11eb-8954-8c6f4b3907da.mp4

**Comment by guozhenyu666** [comment]
可能是windows 的问题, 顺便问一下 如何裁切成一个圆 .... 总不能裁切1:1  然后修成圆吧  感觉有点hack 了

**Comment by guozhenyu666** [comment]
win10 与安卓
