### ISSUE TITLE
 TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by wellfrog1** [chengpeiquan/vue-picture-cropper#9]
经常报这样的错 TypeError: Cannot read property 'substring' of undefined

**Comment by wellfrog1** [comment]
裁剪好的图片转base64失败了，返回的是空

**Comment by wellfrog1** [comment]
这种情况出现在连续多次裁剪图片的时候

**Comment by chengpeiquan** [comment]
收到，我来看看是啥情况~

**Comment by chengpeiquan** [comment]
已发了个小版本修复了这个报错问题，现在如果获取结果失败，base64是空字符串，blob是null
